export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_REQUEST= "FETCH_USER_DATA";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAIL = "FETCH_USER_POSTS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";